---
- name: samsoung play book
  hosts: masternode
  

  tasks:
    - name: copy samsoung.yaml
      copy:
        src: samsoung.yaml
        dest: /home/vagrant/k8s
      become: yes

    - name: deployment
      shell: 'kubectl apply -f /home/vagrant/k8s/samsoung.yaml'
      become: no
