---
- name: samsung play book
  hosts: masternode
  

  tasks:
    - name: copy samsung.yaml
      copy:
        src: samsung.yaml
        dest: /home/vagrant/k8s
      become: yes

    - name: deployment
      shell: 'kubectl apply -f /home/vagrant/k8s/samsung.yaml'
      become: no
